version: 2.1
orbs:
  docker: circleci/docker@0.6.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:12.16.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Unit test
          command: npm run test:unit

workflows:
  build-and-test:
    jobs:
      - build-and-test
  build-and-publish-docker-image:
    jobs:
      - build-and-test
      - docker/publish:
          requires:
            - build-and-test
          context: docker-hub
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: "latest, ${CIRCLE_SHA1:0:7}"
          use-docker-credentials-store: true
