version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:12.16.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Unit test
          command: npm test:unit
workflows:
  build-and-test:
    jobs:
      - build-and-test
